config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"


  resources :tickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
     member do
      post :favorite
      post :unfavorite
     end
  end

  resources :coupons, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
      member do
        post :favorite
        post :unfavorite
        post :add_to_cart
        post :remove_from_cart
      end
  end


  resources :railtickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
      # post :add_to_rail_cart
      # post :remove_from_rail_cart
   end
  end

  resources :parktickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
   end
  end

  resources :metros, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
    end
  end

  resources :comboards, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :tickets
      get :railtickets
      get :favorites
      get :unfavorites
      get :comments
      get :coupons
      get :comboards
      get :parktickets
    end
  end

  resources :articles do
    collection do
      get :visa
      get :direct_flight
      get :lagage
      get :carry
      get :price
      get :checkin
    end
  end

  namespace :admin do
    resources :users
    resources :tickets
    resources :railtickets
    resources :coupons
    resources :comboards
    # resources :orders
    # resources :rail_orders
    resources :parktickets
    resources :metros
    root "tickets#index"
  end

  resources :searches

  # resource :cart
  # resources :orders do
  #   post :checkout_spgateway, on: :member
  # end
  #
  # resource :rail_cart
  # resources :rail_orders do
  #   post :checkout_spgateway1, on: :member
  # end

end

app/models/comboard.rb
class Comboard < ApplicationRecord
  belongs_to :user
  has_many :comments, :as => :commentable
end

app/controllers/admin/comboards_controller.rb
class Admin::ComboardsController < Admin::BaseController
  before_action :set_comboard, only: [:show, :edit, :update, :destroy]

  def index
   @comboards = Comboard.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
   #set_comboard
   @comment = Comment.new
  end

  def edit
   #set_comboard
  end

  def update
   if @comboard.update(comboard_params)
     flash[:notice] = "Message was successfully updated"
     redirect_to admin_comboard_path(@comboard)
   else
     flash.now[:alert] = "Message was failed to update"
     render :edit
   end
  end

  def destroy
   @comboard.destroy
   redirect_to comboards_path
   flash[:alert] = "Message was deleted"
  end

  private

  def set_comboard
   @comboard = Comboard.find(params[:id])
  end


  def comboard_params
   params.require(:comboard).permit(:flight_date_from, :flight_date_to, :departure, :destination, :name, :price, :content)
  end

end

app/controllers/comboards_controller.rb
class ComboardsController < ApplicationController
  before_action :set_comboard, only: [:show, :edit, :update, :destroy]

  def index
    @comboards = Comboard.page(params[:page]).per(4)
    @comboard = Comboard.new
  end

  def new
    @comboard = Comboard.new
  end

  def create
    @comboard = current_user.comboards.new(comboard_params)
    if @comboard.save
      flash[:notice] = "Message was successfully created"
      redirect_to comboards_url
    else
      flash.now[:alert] = "Message was failed to create"
      redirect_to comboards_url
    end
  end

  def show
    #set_comboard

    @comment = Comment.new
  end

  def edit
    #set_comboard
  end

  def update
    if @comboard.update(comboard_params)
      flash[:notice] = "Message was successfully updated"
      redirect_to comboard_path(@comboard)
    else
      flash.now[:alert] = "Message was failed to update"
      render :edit
    end
  end

  def destroy
    @comboard.destroy
    redirect_to comboards_path
    flash[:alert] = "Message was deleted"
  end

  private

  def set_comboard
    @comboard = Comboard.find(params[:id])
  end

  def comboard_params
    params.require(:comboard).permit(:flight_date_from, :flight_date_to, :departure, :destination, :name, :price, :content )
  end

end

app/helpers/comboards_helper.rb
module ComboardsHelper
end

app/views/comboards/edit.html.erb
<%= render partial: "shared/navbar" %>

<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="sidebar-block">
          <%= form_for @comboard do |f| %>
          <form action="javascript:void(0);">
            <h3>輸入您的徵求內容</h3>


            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :destination, "目的地:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :destination, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>

            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :flight_date_from, "期望開始日期" %></label>
                <div class="input1_inner">
                  <%= f.date_field :flight_date_from, class: "input datepicker" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :flight_date_to, "期望結束日期"%></label>
                <div class="input1_inner">
                  <%= f.date_field :flight_date_to, class: "input datepicker" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :departure, "出發地:" %></label>
                <div class="input2_inner">
                    <%= f.text_field :departure, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :destination, "目的地:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :destination, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :price, "期望單價:/張" %></label>
                <div class="input2_inner">
                  <%= f.text_field :price, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :name, "徵求者姓名" %></label>
                <div class="input2_inner">
                  <%= f.text_field :name %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :content, "其他資訊" %></label>
                <div class="input2_inner">
                  <%= f.text_area :content, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="no-padding margin-top text-center" style="margin-top:30px;">
              <%= f.submit '資訊輸入', class: 'btn btn-default btn-cf-submit3', style: 'width:100%;' %>
            </div>
            <div class="clearfix"></div>
          </form>
        <% end %>
        </div>
        <div class="clearfix"></div>
        <div class="margin-top"></div>
      </div>
    </div>
  </div>
</div>
<%= render partial: "shared/footer"%>

app/views/comboards/index.html.erb
<%= render partial: "shared/navbar" %>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-11">
        <div class="blog_content">
          <div class="num-comments">徵求機票留言板</div>
          <% @comboards.each do |comboard| %>
          <div class="comment-block clearfix">
            <div class="caption">
              <div class="top clearfix">
                <div class="txt1">留言者: <a href="#"><%= link_to "#{comboard.user.name}", user_path(comboard.user) %></a></div>
                <span>|</span>
                <div class="txt2">留言時間: <%= comboard.created_at %></div>
                <span>|</span>
                <div class="txt3"><%= link_to '詳情', comboard_path(comboard) %></div>
                <% if current_user == comboard.user %>
                  <div class="txt3"><%= link_to '編輯', edit_comboard_path(comboard) %></div>
                  <div class="txt3"><%= link_to '刪除', comboard_path(comboard), method: :delete, data: {confirm:"Are you sure?"} %> </div>
                <% end %>
              </div>
              <div class="txt">
                機票需求日期: 從 <%= comboard.flight_date_from %> ～ 到 <%= comboard.flight_date_to %><br>
                出發地:<%= comboard.departure %><br>
                目的地: <%= comboard.destination %><br>
                期望價格: <%= comboard.price %><br>
                其他資訊: <%= comboard.content %><br>
              </div>
              <div class="top clearfix">
                <br>
                <div class="txt3"><%= link_to '我有合適機票', new_ticket_path(@ticket) %></div>
                <span>|</span>
                <div class="txt3"><%= link_to '通知買家', comboard_path(comboard) %></div>
              </div>
            </div>
          </div>
          <% end %>
          <div class="text-center"><%= paginate @comboards %></div>
          <div class="live-comment">
            <div class="num-comments">留下您的需求</div>
            <div class="live-comment-title"></div>
            <div class="live-comment-form">
              <div id="note3"></div>
              <div id="fields3">
                <%= form_for @comboard do |f| %>
                <form id="ajax-contact-form3" class="form-horizontal" action="javascript:;">
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.label :flight_date_from, "機票需求開始日期:" %>
                        <%= f.date_field :flight_date_from, class: "form-control" %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.label :flight_date_to, "機票需求結束日期:" %>
                        <%= f.date_field :flight_date_to, class: "form-control" %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.label :departure, "出發地" %>
                        <%= f.text_field :departure, class: "form-control" %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.label :destination, "目的地" %>
                        <%= f.text_field :destination, class: "form-control" %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.label :price, "期望價格" %>
                        <%= f.text_field :price , class: "form-control" %>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <%= f.label :content, "其他資訊" %>
                        <%= f.text_area :content %>
                      </div>
                    </div>
                  </div>
                <%= f.submit '留言' %>
              </form>
              <% end %>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: "shared/footer"%>

app/views/comboards/new.html.erb
<%= form_for @comboard do |f| %>


  <%= f.label :flight_date_from, "Flight_date_from" %>
  <%= f.date_field :flight_date_from %>

  <%= f.label :flight_date_to, "Flight_date_to" %>
  <%= f.date_field :flight_date_to %>

  <%= f.label :departure, "Departure" %>
  <%= f.text_field :departure %>

  <%= f.label :destination, "Destination" %>
  <%= f.text_field :destination %>

  <%= f.label :name, "User Name" %>
  <%= f.text_field :name %>

  <%= f.label :price, "Expecting Price" %>
  <%= f.text_field :price %>

  <%= f.label :content, "Additional Remarkes" %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

app/views/comboards/show.html.erb
<%= render partial: "shared/navbar" %>
<div class="breadcrumbs1_wrapper">
  <div class="container">
    <div class="breadcrumbs1"><a><%= link_to 'Back to 留言板', comboards_path %></a><span>/</span>留言</div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="blog_content">
          <div class="post post-full">
            <div class="post-story">
              <h2>目的地: <%= @comboard.destination %></h2>
              <div class="post-story-info">
                <div class="date1"><%= @comboard.created_at %></div>
                <div class="by">由 <a><%= link_to "#{@comboard.user.name}", user_path(@comboard.user) %></a>張貼</div>
              </div>
              <div class="post-story-body clearfix">
                機票需求日期: <%= @comboard.flight_date_from %> ~ <%= @comboard.flight_date_to %><br>
                出發地: <%= @comboard.departure %><br>
                目的地: <%= @comboard.destination %><br>
                期望價格: NTD$ <%= @comboard.price %><br>
                其他附註: <%= @comboard.content %><br> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @comboard.comments.each do |comment| %>
      <div>
        <h4><%= comment.user.name %></h4>
        <p><%= simple_format comment.content %></p>
        <p class="text-muted">
        <em><%= time_ago_in_words(comment.created_at) %> ago -</em>
        <% if current_user.admin? %>
          <%= link_to "刪除", comboard_comment_path(@comboard, comment), method: :delete, data: {confirm:"Are you sure?"} %>
           <% end %>
        </p>
      </div>
      <hr>
    <% end %>
    <%= form_for [@comboard, @comment] do |f| %>
      <div class="form-group">
        <%= f.text_area :content, placeholder: "留言給徵求者", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "立即聯絡賣家", class: "btn btn-primary" %>
        <%= f.button "取消留言", type: :reset, class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>
<%= render partial: "shared/footer"%>