config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"


  resources :tickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
     member do
      post :favorite
      post :unfavorite
     end
  end

  resources :coupons, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
      member do
        post :favorite
        post :unfavorite
        post :add_to_cart
        post :remove_from_cart
      end
  end


  resources :railtickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
      # post :add_to_rail_cart
      # post :remove_from_rail_cart
   end
  end

  resources :parktickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
   end
  end

  resources :metros, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
    end
  end

  resources :comboards, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :tickets
      get :railtickets
      get :favorites
      get :unfavorites
      get :comments
      get :coupons
      get :comboards
      get :parktickets
    end
  end

  resources :articles do
    collection do
      get :visa
      get :direct_flight
      get :lagage
      get :carry
      get :price
      get :checkin
    end
  end

  namespace :admin do
    resources :users
    resources :tickets
    resources :railtickets
    resources :coupons
    resources :comboards
    # resources :orders
    # resources :rail_orders
    resources :parktickets
    resources :metros
    root "tickets#index"
  end

  resources :searches

  # resource :cart
  # resources :orders do
  #   post :checkout_spgateway, on: :member
  # end
  #
  # resource :rail_cart
  # resources :rail_orders do
  #   post :checkout_spgateway1, on: :member
  # end

end

app/views/shared/_admin_nav_bar.html.erb
<div id="main">
  <div class="top2_wrapper">
    <div class="container">
      <div class="top2 clearfix">
      <header>
        <div class="logo_wrapper">
          <a href="" class="logo">
            <%= link_to tickets_path do %>
              <img src="/images/logo4.jpg" alt="" class="img-responsive">
            <% end %>
          </a>
        </div>
      </header>
      <div class="navbar navbar_ navbar-default">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse navbar-collapse_ collapse">
          <ul class="nav navbar-nav sf-menu clearfix">
            <li class="<%= active_class(admin_tickets_path) %>"><%= link_to '機票清單', admin_tickets_path %><em></em></li>
            <li class="<%= active_class(admin_coupons_path) %>"><%= link_to '兌換卷清單', admin_coupons_path %><em></em></li>
            <li class="<%= active_class(admin_railtickets_path) %>"><%= link_to '高鐵票清單', admin_railtickets_path %><em></em></li>
            <li class="<%= active_class(admin_parktickets_path) %>"><%= link_to '遊園卷清單', admin_parktickets_path %><em></em></li>
            <li class="<%= active_class(admin_comboards_path) %>"><%= link_to '留言板清單', admin_comboards_path %><em></em></li>
            <li class="<%= active_class(admin_user_path(current_user)) %>"><%= link_to '使用者清單', admin_users_path %><em></em></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comments.html.erb
<% commentable.comments.each do |comment| %>
<div>
  <h4><%= link_to "#{comment.user.name}", user_path(comment.user) %></h4>
  <p><%= simple_format comment.content %></p>
  <p class="text-muted">
  <em><%= time_ago_in_words(comment.created_at) %> ago -</em>
  <% if current_user.admin? %>
    <%= link_to "Delete", ticket_comment_path(commentable, comment), method: :delete, data: {confirm:"Are you sure?"} %>
  <% end %>
  </p>
</div>
<hr>
<% end %>

app/views/shared/_coupon_favorite.html.erb
<% if coupon.is_favorited?(current_user) %>
    <%= link_to '不收藏', unfavorite_coupon_path(coupon), method: :post, class: "btn btn-info" %>
<% else %>
    <%= link_to '收藏', favorite_coupon_path(coupon), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_footer.html.erb
<div class="bot1_wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <div class="logo2_wrapper">
          <a href="" class="logo2">
            <%= link_to tickets_path do %>
            <img src="/images/logo4.jpg" alt="" class="img-responsive">
            <% end %>
          </a>
        </div>
        <p>
          We offer ticket exchange platform in Taiwan. Welcome to share and exchange any ticket information on the platform, including flight tickets, flight coupons, HSR tickets, multiday pass, park tickets.
        </p>
        <div class="phone2">(02) 651-651-65 </div>
        <div class="support1"><a href="#">support@new_hold_release.com</a></div>
      </div>
      <div class="col-sm-5">
        <div class="bot1_title">訂閱電子報</div>
        <div class="newsletter_block">
          <div class="txt1">獲得最新機票交換資訊，立刻輸入您的Email</div>
          <div class="newsletter-wrapper clearfix">
            <!-- Begin MailChimp Signup Form -->
           <link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
           <style type="text/css">
               #mc_embed_signup{background:#222222; clear:left; font:14px Helvetica,Arial,sans-serif; }
               /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
                  We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
              /* #mc_embed_signup_scroll{background:black; clear:left; font:14px Helvetica,Arial,sans-serif; } */
           </style>
           <div id="mc_embed_signup">
            <form action="https://facebook.us12.list-manage.com/subscribe/post?u=dff4dee48039e63b2cd2298af&amp;id=401cf3539d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
              <div id="mc_embed_signup_scroll">
                <!-- <label for="mce-EMAIL">Newsletter</label> -->
                <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_dff4dee48039e63b2cd2298af_401cf3539d" tabindex="-1" value=""></div>
                <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn-default btn4"></div>
              </div>
            </form>
           </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="bot2_wrapper">
  <div class="container">
    <div class="left_side">
      Copyright © 2018 <strong>NewHoldRelease</strong> <span>|</span> <a href="#">Privacy Policy</a> <span>|</span>
    </div>
  <div class="right_side">Designed by <strong>NewHoldRelease</strong></div>
</div>

app/views/shared/_navbar.html.erb
<div id="main">
  <div class="top2_wrapper">
    <div class="container">
      <div class="top2 clearfix">
      <header>
        <div class="logo_wrapper">
          <a href="index.html" class="logo">
            <%= link_to tickets_path do %>
              <img src="/images/logo4.jpg" alt="" class="img-responsive">
            <% end %>
          </a>
        </div>
      </header>
      <div class="navbar navbar_ navbar-default">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse navbar-collapse_ collapse">
          <ul class="nav navbar-nav sf-menu clearfix">
            <li class="<%= active_class(tickets_path) %>"><%= link_to '廉航機票', tickets_path %><em></em></li>
            <li class="<%= active_class(coupons_path) %>"><%= link_to '機票兌換卷', coupons_path %><em></em></li>
            <li class="<%= active_class(railtickets_path) %>"><%= link_to '高鐵票', railtickets_path %><em></em></li>
            <li class="<%= active_class(metros_path) %>"><%= link_to '多日周遊券', metros_path %><em></em></li>
            <li class="<%= active_class(parktickets_path) %>"><%= link_to '遊園卷', parktickets_path %><em></em></li>
            <li class="<%= active_class(comboards_path) %>"><%= link_to '需求佈告欄', comboards_path %><em></em></li>
            <li class="<%= active_class(comboards_path) %>"><%= link_to '懶人包首頁', articles_path %><em></em></li>
            <% if current_user %>
              <li class="<%= active_class(user_path(current_user)) %>"><%= link_to '個人資訊', user_path(current_user) %><em></em></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_parkticket_favorite.html.erb
<% if parkticket.is_favorited?(current_user) %>
  <%= link_to '不收藏', unfavorite_parkticket_path(parkticket), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to '收藏', favorite_parkticket_path(parkticket), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_railticket.html.erb
<% @railtickets.each do |railticket| %>
  <div class="col-sm-6 col-md-4">
    <div class="railticket-item">
      <li>



      Train no: <%= railticket.train_no %><br>
      Train date: <%= railticket.train_date %><br>
      Departure time: <%= railticket.departure_time %><br>
      Arrive time: <%= railticket.arrive_time %><br>
      Departure:<%= railticket.departure %><br>
      Destination: <%= railticket.destination %><br>
      Name: <%= railticket.name %><br>
      Price: <%= railticket.price %><br>
      Original Discout: <%= railticket.discount %><br>
      Others: <%= railticket.others %><br>

<br>
</li>
<div class="caption">
  <h3><%= link_to railticket.name, railticket_path(railticket) %></h3>
  <%= link_to 'Show', railticket_path(railticket) %>
  <%= link_to 'Edit', edit_railticket_path(railticket) %>
  <%= render partial: "shared/train_favorite", locals: {ticket: railticket} %>
</div>
</div>
</div>
<% end %>


<div class="text-center">
<%= paginate @railtickets %>
</div>
<%= link_to 'Back to Train Ticket', railtickets_path %>

app/views/shared/_search_coupon.html.erb
<%= render partial: "shared/navbar" %>

<div id="popular_cruises1">
  <div class="container">
    <h2 class="animated">熱門兌換卷搜尋結果</h2>
    <div class="title1 animated">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod <br>tincidunt ut laoreet dolore magna aliquam erat volutpat.
    </div>
    <br><br>
    
    <div id="popular_wrapper" class="animated" data-animation="fadeIn" data-animation-delay="300">
      <div id="popular_inner">
        <div class="">
          <div id="popular">
            <div class="">
              <div class="carousel-box">
                <div class="inner">
                  <div class="carousel main">
                    <ul>
                      <% @search.coupons.each do |coupon| %>
                      <div class="col-sm-6 col-md-4">
                        <li>
                          <div class="popular ">
                            <div class="popular_inner">
                              <figure>
                                <img src="http://placehold.it/370x232" alt="" class="img-responsive">
                                  <div class="over">
                                    <div class="v1"><%= coupon.destination %><span>17 Deal Offers</span></div>
                                    <div class="v2">Lorem ipsum dolor sit amet,concateus.</div>
                                  </div>
                              </figure>
                              <div class="caption">
                                <div class="txt1"><span><%= coupon.destination %></span></div>
                                <div class="txt1"><%= coupon.airline %></div>
                                <div class="txt2">Expiry Date: <%= coupon.coupon_expiry_date %></div>
                                <div class="txt2">使用期間: </div>
                                <div class="txt2"> <%= coupon.flight_date_from %> ~ <%= coupon.flight_date_to %></div>
                                <div class="txt3 clearfix">
                                  <div class="left_side">
                                    <div class="nums"> 18 Reviews</div>
                                  </div>
                                  <div class="right_side">
                                    <%= render partial: "shared/coupon_favorite", locals: {coupon: coupon} %>
                                  </div>
                                  <div class="right_side"><%= link_to '詳情', coupon_path(coupon), class: "btn btn-info" %></div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                      </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="popular_pagination"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_railticket.html.erb
<%= render partial: "shared/navbar" %>

<div id="popular_cruises1">
  <div class="container">
    <h2 class="animated">高鐵票搜尋結果</h2>
    <div class="title1 animated">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod <br>tincidunt ut laoreet dolore magna aliquam erat volutpat.
    </div>
    <br><br>

    <div id="popular_wrapper" class="animated" data-animation="fadeIn" data-animation-delay="300">
      <div id="popular_inner">
        <div class="">
          <div id="popular">
            <div class="">
              <div class="carousel-box">
                <div class="inner">
                  <div class="carousel main">
                    <ul>
                      <% @search.railtickets.each do |railticket| %>
                      <div class="col-sm-6 col-md-4">
                        <li>
                        <div class="popular ">
                          <div class="popular_inner">
                            <figure>
                              <img src="http://placehold.it/370x232" alt="" class="img-responsive">
                                <div class="over">
                                  <div class="v1"><%= railticket.destination %><span>17 Deal Offers</span></div>
                                  <div class="v2">Lorem ipsum dolor sit amet,concateus.</div>
                                </div>
                            </figure>
                            <div class="caption">
                              <div class="txt1"><span><%= railticket.destination %></span></div>
                              <div class="txt1">Departure:<%= railticket.departure %></div>
                              <div class="txt1">Train no: <%= railticket.train_no %></div>
                              <div class="txt2">Train date: <%= railticket.train_date %></div>
                              <div class="txt2">Departure time: <%= railticket.departure_time %></div>
                              <div class="txt3 clearfix">
                                <div class="left_side">
                                  <div class="nums"> 18 Reviews</div>
                                </div>
                                <div class="right_side">
                                 <%= render partial: "shared/train_favorite", locals: {railticket: railticket} %>
                                </div>
                                <div class="right_side"><%= link_to '詳情', railticket_path(railticket), class: "btn btn-info" %></div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="popular_pagination"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_ticket.html.erb
<%= render partial: "shared/navbar" %>

<div id="popular_cruises1">
    <div class="container">
      <h2 class="animated">廉航機票搜尋結果</h2>
      <div class="title1 animated">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod <br>tincidunt ut laoreet dolore magna aliquam erat volutpat.
      </div>
      <br><br>
      
      <div id="popular_wrapper" class="animated" data-animation="fadeIn" data-animation-delay="300">
        <div id="popular_inner">
          <div class="">
            <div id="popular">
              <div class="">
                <div class="carousel-box">
                  <div class="inner">
                    <div class="carousel main">
                      <ul>
                        <% @search.tickets.each do |ticket| %>
                        <div class="col-sm-6 col-md-4">
                          <li>
                           <div class="popular ">
                            <div class="popular_inner">
                              <figure>
                                <img src="http://placehold.it/370x232" alt="" class="img-responsive">
                                  <div class="over">
                                    <div class="v1"><%= ticket.destination %><span>17 Deal Offers</span></div>
                                    <div class="v2">Lorem ipsum dolor sit amet,concateus.</div>
                                  </div>
                              </figure>
                              <div class="caption">
                                <div class="txt1"><span><%= ticket.destination %></span></div>
                                <div class="txt1"><%= ticket.airline %></div>
                                <div class="txt2">Flight No: <%= ticket.flight_no %></div>
                                <div class="txt2">Flight Date: <%= ticket.flight_date %></div>
                                <div class="txt2">Departure: <%= ticket.departure %></div>
                                <div class="txt3 clearfix">
                                  <div class="left_side">
                                    <div class="nums"> 18 Reviews</div>
                                  </div>
                                  <div class="right_side">
                                    <%= render partial: "shared/ticket_favorite", locals: {ticket: ticket} %>
                                  </div>
                                  <div class="right_side"><%= link_to '詳情', ticket_path(ticket), class: "btn btn-info" %></div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                      </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="popular_pagination"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ticket_favorite.html.erb
<% if ticket.is_favorited?(current_user) %>
  <%= link_to '不收藏', unfavorite_ticket_path(ticket), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to '收藏', favorite_ticket_path(ticket), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_train_favorite.html.erb
<% if railticket.is_favorited?(current_user) %>
  <%= link_to '不收藏', unfavorite_railticket_path(railticket), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to '收藏', favorite_railticket_path(railticket), method: :post, class: "btn btn-primary" %>
<% end %>