config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"


  resources :tickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
     member do
      post :favorite
      post :unfavorite
     end
  end

  resources :coupons, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
      member do
        post :favorite
        post :unfavorite
        post :add_to_cart
        post :remove_from_cart
      end
  end


  resources :railtickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
      # post :add_to_rail_cart
      # post :remove_from_rail_cart
   end
  end

  resources :parktickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
   end
  end

  resources :metros, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
    end
  end

  resources :comboards, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :tickets
      get :railtickets
      get :favorites
      get :unfavorites
      get :comments
      get :coupons
      get :comboards
      get :parktickets
    end
  end

  resources :articles do
    collection do
      get :visa
      get :direct_flight
      get :lagage
      get :carry
      get :price
      get :checkin
    end
  end

  namespace :admin do
    resources :users
    resources :tickets
    resources :railtickets
    resources :coupons
    resources :comboards
    # resources :orders
    # resources :rail_orders
    resources :parktickets
    resources :metros
    root "tickets#index"
  end

  resources :searches

  # resource :cart
  # resources :orders do
  #   post :checkout_spgateway, on: :member
  # end
  #
  # resource :rail_cart
  # resources :rail_orders do
  #   post :checkout_spgateway1, on: :member
  # end

end

app/models/cart.rb
class Cart < ApplicationRecord
  # has_many :cart_items, dependent: :destroy
  # has_many :coupons, through: :cart_items


  # def add_cart_item(coupon)
  #   cart_item = cart_items.build( coupon_id: coupon.id, quantity: coupon.quantity)
  #   cart_item.save!
  #   self.cart_items
  # end


  # def subtotal
  #   cart_items.map{|x| x.item_total }.sum
  # end

  # def find_item_by(coupon)
  #   self.cart_items.where(coupon_id: coupon).first
  # end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  # def show
  #   @cart = current_cart
  #   @items = current_cart.cart_items
  #   @order = Order.new
  # end

end

app/views/carts/show.html.erb
<%= render partial: "shared/navbar" %>

<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <section id="cart-list" class="panel">
          <div>
            <h2>機票兌換卷 購物車清單</h2>
          </div>
          <table>
            <tr>
              <th>兌換卷ID</th>
              <th>航空公司</th>
              <th>價格</th>
              <th>數量</th>
              <th>個別總價</th>
              <th></th>
            </tr>
            <% @items.each do |item| %>
            <tr>
              <td><%= item.coupon.id %></td>
              <td><%= item.coupon.airline %><br></td>
              <td>NTD $<%= item.coupon.price %> <br></td>
              <td><%= item.quantity %></td>
              <td><%= item.item_total %></td>
              <td><%= link_to "Detele", remove_from_cart_coupon_path(item.coupon), method: :post, remote: true %> <br></td>
            </tr>
          <% end %>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>總價</td>
            <td class="amount"><%= current_cart.subtotal %></td>
            <td></td>
          </tr>
        </table>
      </section>

      <%= form_for @order do |f| %>
      <section class="panel">
        <h2>輸入聯絡資訊並成立訂單</h2>
          <div class="form-group">
            <%= f.label :name, '姓名:' %>
            <%= f.text_field :name %>
          </div>
          <div class="form-group">
            <%= f.label :phone, '電話:' %>
            <%= f.text_field :phone %>
          </div>
          <div class="form-group">
            <%= f.label :address, '地址:' %>
            <%= f.text_field :address %>
          </div>
      </section>
      <%= f.submit "成立訂單", class: "btn" %>
      <% end %>
      </div>
    </div>
  </div>
</div>
<%= render partial: "shared/footer"%>