config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"


  resources :tickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
     member do
      post :favorite
      post :unfavorite
     end
  end

  resources :coupons, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
      member do
        post :favorite
        post :unfavorite
        post :add_to_cart
        post :remove_from_cart
      end
  end


  resources :railtickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
      # post :add_to_rail_cart
      # post :remove_from_rail_cart
   end
  end

  resources :parktickets, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
   end
  end

  resources :metros, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
    member do
      post :favorite
      post :unfavorite
    end
  end

  resources :comboards, only: [:index, :show, :create, :edit, :new, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :tickets
      get :railtickets
      get :favorites
      get :unfavorites
      get :comments
      get :coupons
      get :comboards
      get :parktickets
    end
  end

  resources :articles do
    collection do
      get :visa
      get :direct_flight
      get :lagage
      get :carry
      get :price
      get :checkin
    end
  end

  namespace :admin do
    resources :users
    resources :tickets
    resources :railtickets
    resources :coupons
    resources :comboards
    # resources :orders
    # resources :rail_orders
    resources :parktickets
    resources :metros
    root "tickets#index"
  end

  resources :searches

  # resource :cart
  # resources :orders do
  #   post :checkout_spgateway, on: :member
  # end
  #
  # resource :rail_cart
  # resources :rail_orders do
  #   post :checkout_spgateway1, on: :member
  # end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  mount_uploader :image, TicketImageUploader 
  belongs_to :user, counter_cache: true


  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :comments, :as => :commentable

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController  
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    #set_ticket
    # @comment = Comment.new
  end

  def edit
    #set_ticket
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket was successfully updated"
      redirect_to admin_ticket_path(@ticket)
    else
      flash.now[:alert] = "Ticket was failed to update"
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_path
    flash[:alert] = "Ticket was deleted"
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:airline, :flight_no, :flight_date, :flight_time, :departure, :destination, :name, :price, :image, :others, :quantity )
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :favorite, :unfavorite]

  def index
    # @tickets = Ticket.all
    # .where({flight_date: (Time.now.midnight - 150.day)..Time.now.midnight}).limit(10)
    # @tickets = Ticket.page(params[:page]).per(9)
    @tickets = Ticket.all.order(favorites_count: :desc).limit(6)
    @search = Search.new 
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      flash[:notice] = "ticket was successfully created"
      redirect_to ticket_path(@ticket)
    else
      flash.now[:alert] = "ticket was failed to create"
      redirect_to root_path
    end
  end

  def show
    #set_ticket
    @comment = Comment.new
  end

  def edit
    #set_ticket
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket was successfully updated"
      redirect_to root_path
    else
      flash.now[:alert] = "Ticket was failed to update"
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to user_path(current_user)
    flash[:alert] = "Ticket was deleted"
  end

  def favorite
    @ticket.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

   def unfavorite
     favorites = Favorite.where(ticket: @ticket, user: current_user)
     favorites.destroy_all
     redirect_back(fallback_location: root_path)
   end

private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end


  def ticket_params
    params.require(:ticket).permit(:airline, :flight_no, :flight_date, :flight_time, :departure, :destination, :name, :price, :image, :others, :quantity )
  end

end

app/helpers/admin/tickets_helper.rb
module Admin::TicketsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/tickets/edit.html.erb
<%= render partial: "shared/admin_nav_bar" %>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-2">
        <div class="sidebar-block">
          <%= form_for [:admin, @ticket] do |f| %>
          <form action="javascript:void(0);">
            <h3>輸入您的票券</h3>

            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :airline, "廉航航空公司:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :airline %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :flight_no, "航班號碼:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :flight_no, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :flight_date, "出發日期:" %></label>
                <div class="input1_inner">
                  <%= f.date_field :flight_date, class: "input datepicker"  %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :flight_time, "起飛時間:" %></label>
                <div class="input1_inner">
                  <%= f.time_field :flight_time, class: "input timepicker" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :departure, "出發地:" %></label>
                <div class="input2_inner">
                    <%= f.text_field :departure, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :destination, "目的地:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :destination, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :name, "機票姓名:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :name, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :price, "欲售價格:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :price, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :quantity, "機票張數:" %></label>
                <div class="input2_inner">
                  <%= f.text_field :quantity, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :image, "選擇機票照片:" %></label>
                <%= f.file_field :image, class: "input" %>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 no-padding margin-top">
              <div class="input1_wrapper">
                <label><%= f.label :others, "其他資訊" %></label>
                <div class="input2_inner">
                  <%= f.text_area :others, class: "input" %>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="no-padding margin-top text-center" style="margin-top:30px;">
              <%= f.submit '資訊輸入', class: 'btn btn-default btn-cf-submit3', style: 'width:100%;' %>
            </div>
            <div class="clearfix"></div>
          </form>
        <% end %>
        </div>
        <div class="clearfix"></div>
        <div class="margin-top"></div>
      </div>
    </div>
  </div>
</div>
<%= render partial: "shared/footer"%>

app/views/admin/tickets/index.html.erb
<%= render partial: "shared/admin_nav_bar" %>
<div class="container">
  <h1>機票清單</h1>
  <div class="row">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Ticket ID</th>
          <th>Airline</th>
          <th>Flight No.</th>
          <th>Flight date</th>
          <th>Flight time</th>
          <th>Departure</th>
          <th>Destination</th>
          <th>User Name</th>
          <th>Price</th>
          <th>Others</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
    </thead>
    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <th scope="row"><%= ticket.id %></th>
          <td><%= ticket.airline %></td>
          <td><%= ticket.flight_no %></td>
          <td><%= ticket.flight_date %></td>
          <td><%= ticket.flight_time %></td>
          <td><%= ticket.departure %></td>
          <td><%= ticket.destination %></td>
          <td><%= ticket.name %></td>
          <td><%= ticket.price %></td>
          <td><%= ticket.others %></td>
          <td><%= link_to 'Show', admin_ticket_path(ticket) %></td>
          <td><%= link_to 'Edit', edit_admin_ticket_path(ticket) %></td>
          <td> <%= link_to 'Delete', admin_ticket_path(ticket), method: :delete, data: {confirm:"Are you sure?"} %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @tickets %>
  </div>
</div>
<%= render partial: "shared/footer"%>

app/views/admin/tickets/show.html.erb
<%= render partial: "shared/admin_nav_bar" %>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <div class="blog_content">
          <div class="post post-full">
            <h3 class="hch">To <%= @ticket.destination %></h3>
            <div class="clearfix"></div>
              <p class="address">Airline: <%= @ticket.airline %></p>
              <div class="post-header">
                <div class="post-slide">
                  <div id="sl1">
                    <div class="sl1_pagination"></div>
                    <div class="carousel-box">
                      <div class="inner">
                        <div class="carousel main">
                          <ul>
                            <li>
                              <div class="sl1">
                                <div class="sl1_inner">
                                  <img src="http://placehold.it/370x232" alt="" class="img-responsive">
                                  <!-- <img src=<%= @ticket.image.url %> alt="ticket-image" class="img-responsive" /> -->
                                </div>
                              </div>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="post-story">
                <hr>
                <div class="post-story-body clearfix">
                <h3>Flight date: <%= @ticket.flight_date %>; <%= @ticket.flight_time %></h3>
                <ul>
                    <li>Departure: <%= @ticket.departure %></li>
                    <li>Destination: <%= @ticket.destination %></li>
                </ul>
                <hr>
                <h4>Details:</h4>
                <ul>
                  <li>From <%= @ticket.departure %></li>
                  <li>To <%= @ticket.destination %></li>
                  <li><%= @ticket.airline %></li>
                  <li>Quantity: <%= @ticket.quantity %></li>
                </ul>
                <p>Others: <%= @ticket.others %></p>
                  <div class="right_side">
                    <%= link_to 'Edit', edit_admin_ticket_path(@ticket), class: "btn btn-info" %> |
                    <%= link_to 'Delete', admin_ticket_path(@ticket), method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-info"  %>
                  </div>
                  <div class="right_side">
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="sidebar-block">
            <form action="javascript:void(0);">
             <div class="col-sm-12 no-padding margin-top">
                <div class="input1_wrapper">
                  <label class="col-md-6" style="padding-left:0;padding-top:12px;font-weight:500;color:#464646;font-size:13px;">
                    建議售價:
                  </label>
                  <div class="col-md-6 price-total-left" style="padding-right:0;padding-left:0;">
                      <span class="red">NTD$ <%= @ticket.price %></span>
                  </div>
                  <label class="col-md-6" style="padding-left:0;padding-top:12px;font-weight:500;color:#464646;font-size:13px;">
                  數量:
                  </label>
                  <div class="col-md-6 price-total-left" style="padding-right:0;padding-left:0;margin-top: 12px;">
                  <h3><%= @ticket.quantity %></h3>
                </div>
                </div>
              </div>
              <div class="clearfix"></div>
            <div class="clearfix"></div>
          </form>
        </div>
        <div class="clearfix"></div>
        <div class="margin-top"></div>
      </div>
    </div>
  </div>
</div>
<%= render partial: "shared/footer"%>